version: '3'
services:
  api:
    build:
      context: .
      dockerfile: ./infra/docker/api.dockerfile
    tty: true
    volumes:
      - ./app:/var/task
      - ./scripts:/var/scripts
    expose:
      - "80"
    ports:
      - 0.0.0.0:8888:80
    # Override lambda entry point to revert to default docker behaviour
    entrypoint: ""
    command: "uvicorn adapter.into.fastapi.main:app --host 0.0.0.0 --port 80"
