version: '3'
services:
  api:
    build:
      context: .
      dockerfile: ./infra/docker/api.dockerfile
    tty: true
    volumes:
      - ./app:/app
      - ./scripts:/scripts
    expose:
      - "80"
    ports:
      - 0.0.0.0:8888:80
  
  lambda:
    build:
      context: .
      dockerfile: ./infra/docker/lambda-api.dockerfile
    tty: true
    volumes:
      - ./app:/app
      - ./scripts:/scripts
    expose:
      - "8080"
    ports:
      - 0.0.0.0:9000:8080
