version: 2.1

orbs:
  python: circleci/python@1.2


jobs:
  build-and-test:
    machine:
      - image: cimg/python:3.8
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - run: make build
      - run: make test
  deploy:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - run: make deploy
# Invoke jobs via workflows
workflows:
  main:
    jobs:
      - build-and-test
      - deploy:
          name: deploy
          requires:
            - build-and-test
